spring:
  application:
    name: ebooklib
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: schema
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
