spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebooklib_db
    username: ebooklib_user
    password: ebooklib_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # For development, automatically update schema
  liquibase:
    contexts: schema,test-data

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: ebook-library-files
