spring:
  liquibase:
    contexts: schema,test-data
  h2:
    console:
      enabled: true

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: ebook-library-files